exports.sampleData = [{ id: 'pokéworks-new-york-2',
    name: 'Pokéworks',
    image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/TWI7lrMn8zpKf6CLahZWqw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/pok%C3%A9works-new-york-2?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 1461,
    categories: [ [Object], [Object], [Object] ],
    rating: 4,
    coordinates: { latitude: 40.7515934305237, longitude: -73.98588180542 },
    transactions: [ 'delivery', 'pickup' ],
    price: '$$',
    location:
     { address1: '63 W 37th St',
       address2: '',
       address3: '',
       city: 'New York',
       zip_code: '10018',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+12125758881',
    display_phone: '(212) 575-8881',
    distance: 154.30936110419998 },
  { id: 'shake-shack-new-york-34',
    name: 'Shake Shack',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/U1z1Eouy8ZQw1fwzcCjcGA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/shake-shack-new-york-34?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 145,
    categories: [ [Object], [Object], [Object] ],
    rating: 4,
    coordinates: { latitude: 40.751171, longitude: -73.988136 },
    transactions: [],
    price: '$$',
    location:
     { address1: '1333 Broadway',
       address2: null,
       address3: '',
       city: 'New York',
       zip_code: '10018',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+16462300696',
    display_phone: '(646) 230-0696',
    distance: 52.33092809207999 },
  { id: 'the-cinnamon-snail-new-york-2',
    name: 'The Cinnamon Snail',
    image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/Vm2Ec5GOIeqq67REKjaSEQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/the-cinnamon-snail-new-york-2?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 731,
    categories: [ [Object] ],
    rating: 4.5,
    coordinates: { latitude: 40.749584197998, longitude: -73.9916763305664 },
    transactions: [],
    price: '$',
    location:
     { address1: '',
       address2: null,
       address3: '',
       city: 'New York',
       zip_code: '10121',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+12126957454',
    display_phone: '(212) 695-7454',
    distance: 406.864004628 },
  { id: 'barn-joo-35-new-york',
    name: 'Barn Joo 35',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/_l1ZhP22bulR2pkNTowONA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/barn-joo-35-new-york?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 535,
    categories: [ [Object], [Object], [Object] ],
    rating: 4,
    coordinates: { latitude: 40.749641418457, longitude: -73.9858245849609 },
    transactions: [],
    price: '$$',
    location:
     { address1: '34 W 35th St',
       address2: '',
       address3: '',
       city: 'New York',
       zip_code: '10001',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+12125644430',
    display_phone: '(212) 564-4430',
    distance: 219.8277973 },
  { id: 'izakaya-mew-new-york-3',
    name: 'Izakaya MEW',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/pQ7i8HA6ivMmo5HHw11DNg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/izakaya-mew-new-york-3?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 1427,
    categories: [ [Object], [Object], [Object] ],
    rating: 4,
    coordinates: { latitude: 40.7503134797577, longitude: -73.9863838167321 },
    transactions: [],
    price: '$$',
    location:
     { address1: '53 W 35th St',
       address2: '',
       address3: '',
       city: 'New York',
       zip_code: '10001',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+16463689384',
    display_phone: '(646) 368-9384',
    distance: 134.1755360068 },
  { id: 'topokee-new-york-2',
    name: 'Topokee',
    image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/dqq9W1UrWeQlq5kG2VgL2w/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/topokee-new-york-2?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 38,
    categories: [ [Object], [Object], [Object] ],
    rating: 4,
    coordinates: { latitude: 40.75269, longitude: -73.98518 },
    transactions: [ 'delivery', 'pickup' ],
    price: '$$',
    location:
     { address1: '68 W 39th St',
       address2: null,
       address3: null,
       city: 'New York',
       zip_code: '10018',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+12128406633',
    display_phone: '(212) 840-6633',
    distance: 263.646263084 },
  { id: 'poketeria-new-york',
    name: 'Poketeria',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/3-ZhS8Th__JzLB3FdGXA5g/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/poketeria-new-york?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 139,
    categories: [ [Object], [Object], [Object] ],
    rating: 4.5,
    coordinates: { latitude: 40.7496522367001, longitude: -73.9833162724972 },
    transactions: [ 'pickup' ],
    price: '$$',
    location:
     { address1: '3 E 36th St',
       address2: null,
       address3: '',
       city: 'New York',
       zip_code: '10016',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+12126898985',
    display_phone: '(212) 689-8985',
    distance: 384.86081846679997 },
  { id: 'chick-fil-a-new-york-6',
    name: 'Chick-fil-A',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/PI1WrfjD6yWkK6jZ5rivqg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/chick-fil-a-new-york-6?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 429,
    categories: [ [Object], [Object] ],
    rating: 4,
    coordinates: { latitude: 40.751739, longitude: -73.986051 },
    transactions: [],
    price: '$',
    location:
     { address1: '1000 Avenue Of The Americas',
       address2: '',
       address3: '',
       city: 'New York',
       zip_code: '10018',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+12127049920',
    display_phone: '(212) 704-9920',
    distance: 148.2958288399 },
  { id: 'beyond-sushi-herald-square-new-york',
    name: 'Beyond Sushi Herald Square',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/l1Rmn5Ubufqn-0sNBlYEYA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/beyond-sushi-herald-square-new-york?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 65,
    categories: [ [Object], [Object], [Object] ],
    rating: 4.5,
    coordinates: { latitude: 40.75247, longitude: -73.98845 },
    transactions: [],
    price: '$$',
    location:
     { address1: '134 West 37th St',
       address2: null,
       address3: '',
       city: 'New York',
       zip_code: '10018',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+12125640869',
    display_phone: '(212) 564-0869',
    distance: 160.62474278823998 },
  { id: 'bombay-sandwich-new-york-19',
    name: 'Bombay Sandwich',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/TvQRuxTSvkKUl5l3YfSecA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/bombay-sandwich-new-york-19?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 22,
    categories: [ [Object], [Object], [Object] ],
    rating: 4.5,
    coordinates: { latitude: 40.75202, longitude: -73.99121 },
    transactions: [ 'delivery', 'pickup' ],
    price: '$$',
    location:
     { address1: '224 W 35th St',
       address2: '',
       address3: '',
       city: 'New York',
       zip_code: '10001',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+12125648418',
    display_phone: '(212) 564-8418',
    distance: 323.72340808599995 },
  { id: 'trademark-taste-and-grind-new-york',
    name: 'Trademark Taste & Grind',
    image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/7ReJsWEG_HyleY_07cRTEQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/trademark-taste-and-grind-new-york?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 222,
    categories: [ [Object], [Object], [Object] ],
    rating: 4.5,
    coordinates: { latitude: 40.7502555847168, longitude: -73.9854583740234 },
    transactions: [],
    price: '$$',
    location:
     { address1: '38 W 36th St',
       address2: null,
       address3: '',
       city: 'New York',
       zip_code: '10018',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+16468582320',
    display_phone: '(646) 858-2320',
    distance: 200.40884746796 },
  { id: 'balade-your-way-new-york-2',
    name: 'Balade - Your Way',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/8jiz1ZkDQowveuY6s8mD_Q/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/balade-your-way-new-york-2?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 166,
    categories: [ [Object], [Object] ],
    rating: 4.5,
    coordinates: { latitude: 40.7524299621582, longitude: -73.9887237548828 },
    transactions: [ 'delivery', 'pickup' ],
    price: '$$',
    location:
     { address1: '144 West 37th St',
       address2: null,
       address3: '',
       city: 'New York',
       zip_code: '10018',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+12126956969',
    display_phone: '(212) 695-6969',
    distance: 176.70307936584 },
  { id: 'good-seed-new-york-2',
    name: 'Good Seed',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/e2s_WR6PMhVV-G4xFKlPeQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/good-seed-new-york-2?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 63,
    categories: [ [Object], [Object] ],
    rating: 4.5,
    coordinates: { latitude: 40.75204, longitude: -73.99076 },
    transactions: [],
    price: '$$',
    location:
     { address1: '213 W 35th St',
       address2: '',
       address3: null,
       city: 'New York',
       zip_code: '10001',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+13473794855',
    display_phone: '(347) 379-4855',
    distance: 283.76972403179997 },
  { id: 'woorijip-authentic-korean-food-new-york',
    name: 'Woorijip Authentic Korean Food',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/10uvZ_FssajuOS6k2T3RGw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/woorijip-authentic-korean-food-new-york?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 2211,
    categories: [ [Object] ],
    rating: 4,
    coordinates: { latitude: 40.74747, longitude: -73.98648 },
    transactions: [],
    price: '$',
    location:
     { address1: '12 W 32nd St',
       address2: '',
       address3: '',
       city: 'New York',
       zip_code: '10001',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+12122441115',
    display_phone: '(212) 244-1115',
    distance: 424.5181747468 },
  { id: 'broadway-bites-new-york-2',
    name: 'Broadway Bites',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/6yuXVcX2f478HpvLs9KiXA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/broadway-bites-new-york-2?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 185,
    categories: [ [Object], [Object] ],
    rating: 4,
    coordinates: { latitude: 40.74903, longitude: -73.98804 },
    transactions: [],
    price: '$$',
    location:
     { address1: '33rd & Broadway',
       address2: '',
       address3: '',
       city: 'New York',
       zip_code: '10001',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '',
    display_phone: '',
    distance: 237.313437334 },
  { id: 'xian-famous-foods-new-york-14',
    name: 'Xi\'an Famous Foods',
    image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/uWw6F6Y3NsuqhWir_zVceQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/xian-famous-foods-new-york-14?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 413,
    categories: [ [Object], [Object], [Object] ],
    rating: 4,
    coordinates: { latitude: 40.747844, longitude: -73.983901 },
    transactions: [],
    price: '$',
    location:
     { address1: '14 E 34th St',
       address2: '',
       address3: '',
       city: 'New York',
       zip_code: '10016',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '',
    display_phone: '',
    distance: 476.8285805352 },
  { id: 'elias-cinco-de-mayo-new-york-2',
    name: 'Elias\' Cinco de Mayo',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/affXn0SJKEMB_pYOLKjRKg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/elias-cinco-de-mayo-new-york-2?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 35,
    categories: [ [Object] ],
    rating: 4.5,
    coordinates: { latitude: 40.75255, longitude: -73.98864 },
    transactions: [ 'delivery', 'pickup' ],
    price: '$',
    location:
     { address1: '144 W 37th St',
       address2: '',
       address3: null,
       city: 'New York',
       zip_code: '10018',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+12129120044',
    display_phone: '(212) 912-0044',
    distance: 176.70307936584 },
  { id: 'the-kati-roll-company-new-york-5',
    name: 'The Kati Roll Company',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/zEIaBeUkW7Odz_EKBcIHMA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/the-kati-roll-company-new-york-5?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 1146,
    categories: [ [Object], [Object] ],
    rating: 4,
    coordinates: { latitude: 40.7528, longitude: -73.98458 },
    transactions: [],
    price: '$',
    location:
     { address1: '49 W 39th St',
       address2: null,
       address3: '',
       city: 'New York',
       zip_code: '10018',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+12127304280',
    display_phone: '(212) 730-4280',
    distance: 316.08515857799995 },
  { id: 'zen-ramen-and-sushi-new-york',
    name: 'Zen Ramen & Sushi',
    image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/ooMAALmK5XAVDvjmOSNxhw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/zen-ramen-and-sushi-new-york?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 237,
    categories: [ [Object], [Object], [Object] ],
    rating: 4,
    coordinates: { latitude: 40.751743, longitude: -73.98899 },
    transactions: [ 'pickup' ],
    price: '$$',
    location:
     { address1: '150 W 36 street',
       address2: '',
       address3: '',
       city: 'New York',
       zip_code: '10018',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+16468707509',
    display_phone: '(646) 870-7509',
    distance: 137.98947868599998 },
  { id: 'crisp-new-york-2',
    name: 'Crisp',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/iqZU39fOwPBsKqwNq0to3w/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/crisp-new-york-2?adjust_creative=TuI7KPQ2iOcLaRBdE3LpMA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TuI7KPQ2iOcLaRBdE3LpMA',
    review_count: 324,
    categories: [ [Object], [Object], [Object] ],
    rating: 4,
    coordinates: { latitude: 40.753987, longitude: -73.986011 },
    transactions: [ 'delivery', 'pickup' ],
    price: '$$',
    location:
     { address1: '110 W 40th St',
       address2: '',
       address3: '',
       city: 'New York',
       zip_code: '10018',
       country: 'US',
       state: 'NY',
       display_address: [Object] },
    phone: '+12126610000',
    display_phone: '(212) 661-0000',
    distance: 348.2041409904 }];
    